In [3]:
import numpy as np
from matplotlib import style
import pandas as pd 

In [4]:
df = pd.read_csv(r".\data\ipl.csv")

In [5]:
df.head(5)

one       two
0  0.227680  0.858204
1  0.979188  0.077151
2  0.504577  0.553114
3  0.058132  0.528098
4  0.775343  0.217922

In [6]:
X = df.values

In [7]:
X[0:10]

array([[0.22767982, 0.85820415],
       [0.97918822, 0.07715065],
       [0.5045766 , 0.55311441],
       [0.0581324 , 0.52809798],
       [0.77534302, 0.21792169],
       [0.55042383, 0.47085982],
       [0.04578654, 0.91857895],
       [0.58576994, 0.05803225],
       [0.70907217, 0.58187366],
       [0.01850393, 0.88652292]])

In [42]:
import numpy as np
import math 

class K_Means:
    def __init__(self, k,  max_iterations = 500):
        self.k = k
        self.max_iterations = max_iterations
        
    def Euclidean_distance(self, feat_one, feat_two):
        squared_distance = 0;
        #Assuming correct input to the function where the lengths of two features are the same
        for i in range(len(feat_one)):
                squared_distance += (feat_one[i] - feat_two[i])**2
        ed =  math.sqrt(squared_distance)
        return ed;      

    def fit(self, data):

        self.centroids = {}

        #initialize the centroids, the first 'k' elements in the dataset will be our initial centroids
        for i in range(self.k):
            self.centroids[i] = data[i]

        #begin iterations
        for i in range(self.max_iterations):
            self.classes = {}
            for i in range(self.k):
                self.classes[i] = []

            #find the distance between the point and cluster; choose the nearest centroid
            for features in data:
                distances = [self.Euclidean_distance(features, self.centroids[centroid]) for centroid in self.centroids]
                classification = distances.index(min(distances))
                self.classes[classification].append(features)

            #average the cluster datapoints to re-calculate the centroids
            for classification in self.classes:
                self.centroids[classification] = np.average(self.classes[classification], axis = 0)#average an array
            
        return self.classes


In [ ]:
#1 Initialize the centroids
#2 Loop
#3 Calculate the classes and re calculate the centroids
#4 self.centroids keep and update the centroids data and can not be reassigned. But self. classes can be re assigned
#5 return self.classes

In [29]:
#so I need to practice 

In [43]:
df = pd.read_csv(r".\data\ipl.csv")

In [44]:
df = df[['one', 'two']]

In [45]:
X = df.values

In [46]:
km = K_Means(3)

In [47]:
km.fit(X)

{0: [array([0.22767982, 0.85820415]),
  array([0.0581324 , 0.52809798]),
  array([0.04578654, 0.91857895]),
  array([0.01850393, 0.88652292]),
  array([0.06942298, 0.85812767]),
  array([0.08497508, 0.99112246]),
  array([0.03563268, 0.58747382]),
  array([0.00559106, 0.7325277 ]),
  array([0.0134452 , 0.50168543]),
  array([0.29440819, 0.69865184]),
  array([0.00175186, 0.57179319]),
  array([0.3078315, 0.8873374]),
  array([0.07527233, 0.52224538]),
  array([0.05200194, 0.93592772]),
  array([0.06508554, 0.95788256]),
  array([0.1434226 , 0.69115503]),
  array([0.09883778, 0.62611036]),
  array([0.28369001, 0.80010687]),
  array([0.21885608, 0.91129057]),
  array([0.21326108, 0.67352195]),
  array([0.00712644, 0.92559927]),
  array([0.15755852, 0.79832911]),
  array([0.11119696, 0.80960918]),
  array([0.16583791, 0.86142626]),
  array([0.06012137, 0.8400569 ]),
  array([0.07123126, 0.61004474])],
 1: [array([0.97918822, 0.07715065]),
  array([0.77534302, 0.21792169]),
  array([0.5857